### ISSUE TITLE
Pdf version of courses

### ISSUE THREAD

**Issue by alinakhay** [orsenthil/coursedocs#1]
First of all, thanks for this repository!
I know the coursedocs website was build with readthedocs theme and hence the pdf version for it is hosted somewhere and can be downloaded. My question is how to extract that pdf, for example gatech cs6400. 
(for example http://media.readthedocs.org/pdf/django-tastypie/latest/django-tastypie.pdf)

Thanks!

**Comment by orsenthil** [comment]
Hi @alinakhay  - I have discontinued this project as the copyright of the transcript of the videos were questionable. I will be writing something that will be helpful to online learners.
